version: "3.3"

services:
  idpkit:
    image: teddysmartb/smartb-idpkit:latest
    container_name: idpkit
    environment:
      WALTID_DATA_ROOT: /waltid/idp
      WALTID_WALLET_BACKEND_PORT: 8091
      LETSENCRYPT_HOST: idp.did.smart-b.io
      VIRTUAL_HOST: idp.did.smart-b.io
      VIRTUAL_PORT: 8091
    volumes:
      - ./waltid/idp:/waltid/idp
    command: ["run", "--bind-all"]
    #command: "config --oidc clients register -r *" # Start the container with this command to generate a new client_id/secret
    ports:
      - "8091:8091"

  walletkit:
    image: waltid/walletkit:latest  # backend docker image
    container_name: walletkit
    environment:
      WALTID_DATA_ROOT: /waltid/wallet
      WALTID_WALLET_BACKEND_PORT: 8092
      LETSENCRYPT_HOST: wallet.did.smart-b.io
      VIRTUAL_HOST: wallet.did.smart-b.io
      VIRTUAL_PORT: 8092
    command: ["run"]

networks:
  default:
    external:
      name: nginx-proxy
