version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    environment:
#      KC_DB_URL: "jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_KEYCLOAK_DB}"
#      KC_DB_PASSWORD: ${POSTGRES_PASS}
#      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_HOSTNAME: localhost:8080
      KEYCLOAK_FRONTEND_URL: "http://localhost:8080"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_SCHEMA: "public"
      KC_PROXY: "edge"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      PROXY_ADDRESS_FORWARDING: "true"
      JDBC_PARAMS: "ssl=false"
#      LETSENCRYPT_HOST: ${AUTH_HOST_NAME},tmp.${AUTH_HOST_NAME}
#      VIRTUAL_HOST: ${AUTH_HOST_NAME},tmp.${AUTH_HOST_NAME}
#      VIRTUAL_PORT: 8080
    ports:
      - "8080:8080"
    command: ["start-dev", "--health-enabled=true", "--log-level INFO", "--features=preview"]

#networks:
#  default:
#    external:
#      name: nginx-proxy
