apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-smartbe-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-smartbe-pv
