kind: Job
apiVersion: batch/v1
metadata:
  name: idp-create-client
spec:
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: idp-create-client
          image: smartbcity/smartb-idp:0.0.1
          volumeMounts:
            - mountPath: "/waltid/idp/data/"
              name: idp-data
          env:
            - name: WALTID_DATA_ROOT
              value: "/waltid/idp"
            - name: WALTID_CONFIG_PATH
              value: "/waltid/idp/config/"
          args:
            - config
            - --oidc
            - clients
            - register
            - --all-redirect-uris
          ports:
            - containerPort: 8080
              name: http-api
      volumes:
        - name: idp-data
          persistentVolumeClaim:
            claimName: idp-data-volume-claim
