kind: Deployment
apiVersion: apps/v1
metadata:
  name: did-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: did-gateway
  template:
    metadata:
      labels:
        app: did-gateway
      annotations:
        deployment/id: "_DEFAULT_DEPLOYMENT_"
    spec:
      containers:
        - name: did-gateway
          image: smartbcity/did-gateway:0.0.8
          imagePullPolicy: Always
          env:
            - name: IDP_URL
              value: "http://idp.c2jn:8091"
            - name: IDP_CLIENT-ID
              value: "ztwxUw4ZE0uxDwoxfvrond517BDMO60yEbtmTF1mocc"
            - name: IDP_CLIENT-SECRET
              value: "ho1feqg5plQvWqhZEQ8GF5lbgIRWInv1CVUGnKaCLGI"
            - name: WALLET_URL
              value: "http://wallet.c2jn:8092"
            - name: ISSUER_URL
              value: "http://wallet.c2jn:8092"
            - name: TARGET-IDP_URL
              value: "http://keycloak.c2jn:8080"
            - name: TARGET-IDP_REALM
              value: "smartb"
            - name: TARGET-IDP_CLIENT-ID
              value: "token-exchange"
            - name: TARGET-IDP_CLIENT-SECRET
              value: "dcsaBAt6oJZeUOn8MrHFcrCcT6WlDomv"
          ports:
            - containerPort: 8090
              name: http-api
---
apiVersion: v1
kind: Service
metadata:
  name: did-gateway
spec:
  selector:
    app: did-gateway
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 32090
  type: NodePort
