apiVersion: v1
kind: ConfigMap
metadata:
  name: idp-config
data:
  verifier-config.json: |
    {
      "verifierUiUrl": "http://idp.c2jn:8091/sharecredential?state=",
      "verifierApiUrl": "http://idp.c2jn:8091/api/siop/default",
      "additionalPolicies": [
      ],
      "wallets": {
        "walt.id": {
          "id": "walt.id",
          "url": "http://wallet.c2jn:8092",
          "presentPath": "api/siop/initiatePresentation/",
          "receivePath" : "api/siop/initiateIssuance/",
          "description": "walt.id web wallet"
        }
      }
    }
  idp-config.json: |
    {
      "externalUrl": "http://idp.c2jn:8091",
      "fallbackAuthorizationMode": "SIOP",
      "claimConfig": {
        "vc_mappings": [
          {
            "scope": [ "profile" ],
            "claim": "name",
            "credentialType": "ConnectIdCredential",
            "valuePath": "$.credentialSubject.firstName $.credentialSubject.familyName"
          },
          {
            "scope": [ "profile" ],
            "claim": "family_name",
            "credentialType": "ConnectIdCredential",
            "valuePath": "$.credentialSubject.familyName"
          },
          {
            "scope": [ "profile" ],
            "claim": "given_name",
            "credentialType": "ConnectIdCredential",
            "valuePath": "$.credentialSubject.firstName"
          },
          {
            "scope": [ "profile" ],
            "claim": "userEmail",
            "credentialType": "ConnectIdCredential",
            "valuePath": "$.credentialSubject.email"
          }
        ],
        "default_vp_token_claim": {
          "presentation_definition": {
            "id": "1",
            "input_descriptors": [
              {
                "id": "1",
                "constraints": {
                  "fields": [
                    {
                      "id": "1",
                      "path": [ "$.type" ],
                      "filter": { "const":  "ConnectIdCredential" }
                    }
                  ]
                }
              }
            ]
          }
        }
      }
    }
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: idpkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idpkit
  template:
    metadata:
      labels:
        app: idpkit
      annotations:
        deployment/id: "_DEFAULT_DEPLOYMENT_"
    spec:
      containers:
        - name: idpkit
          image: smartbcity/smartb-idp:0.0.1
          volumeMounts:
            - name: idp-config
              mountPath: "/waltid/idp/config/"
              readOnly: true
            - mountPath: "/waltid/idp/data/"
              name: idp-data
          env:
            - name: WALTID_DATA_ROOT
              value: "/waltid/idp"
            - name: WALTID_CONFIG_PATH
              value: "/waltid/idp/config/"
          args:
            - run
            - --bind-all
          ports:
            - containerPort: 8080
              name: http-api
      volumes:
        - name: idp-config
          configMap:
            name: idp-config
        - name: idp-data
          persistentVolumeClaim:
            claimName: nfs-smartbe-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: idp
spec:
  selector:
    app: idpkit
  ports:
    - port: 8091
      targetPort: 8080
      nodePort: 32091
  type: NodePort
