apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
      nodePort: 32080
  selector:
    app: keycloak
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:20.0.3
          ports:
            - containerPort: 8080
              name: http
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start-dev", "--health-enabled=true", "--log-level INFO", "--features=preview"]
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres-keycloak/keycloak
            - name: KC_DB_PASSWORD
              value: password
            - name: KC_DB_USERNAME
              value: postgres
            - name: KC_DB
              value: postgres
