apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-keycloak
spec:
  selector:
    matchLabels:
      app: postgres-keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      containers:
        - name: postgres-keycloak
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: keycloak
      # TODO: Add persistent volumes
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
  labels:
    app: postgres-keycloak
spec:
  ports:
    - port: 5432
      name: postgres-keycloak
  selector:
    app: postgres-keycloak
  type: ClusterIP
