apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-config
data:
  issuer-config.json: |
    {
      "issuerUiUrl": "http://walletkit:8092",
      "issuerApiUrl": "http://walletkit:8092/issuer-api/default",
      "credentialTypes": [ "VerifiableId" ],
      "wallets": {
        "waltid": {
          "id": "waltid",
          "url": "http://walletkit:8092",
          "presentPath": "api/siop/initiatePresentation/",
          "receivePath" : "api/siop/initiateIssuance/",
          "description": "walt.id web wallet"
        }
      }
    }

  verifier-config.json: |
    {
      "verifierUiUrl": "http://walletkit:8092",
      "verifierApiUrl": "http://walletkit:8092/verifier-api/default",
      "wallets": {
        "walt.id": {
          "id": "walt.id",
          "url": "http://walletkit:8092",
          "presentPath": "api/siop/initiatePresentation/",
          "receivePath" : "api/siop/initiateIssuance/",
          "description": "walt.id web wallet"
        }
      }
    }

  wallet-config.json: |
    {
      "walletUiUrl": "http://localhost:3000",
      "walletApiUrl": "http://walletkit:8092/api",
      "issuers": {
        "waltid": {
          "id": "waltid",
          "url": "http://walletkit:8092/issuer-api/default/oidc",
          "description": "walt.id Issuer Portal"
        }
      }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: walletkit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: walletkit
  template:
    metadata:
      labels:
        app: walletkit
      annotations:
        deployment/id: "_DEFAULT_DEPLOYMENT_"
    spec:
      containers:
        - name: walletkit
          image: waltid/walletkit:latest
          volumeMounts:
            - name: wallet-config
              mountPath: "/waltid/wallet/config/"
              readOnly: true
            - mountPath: "/waltid/wallet/data/"
              name: wallet-data
          env:
            - name: WALTID_DATA_ROOT
              value: "/waltid/wallet"
            - name: WALTID_WALLET_BACKEND_BIND_ADDRESS
              value: 0.0.0.0
          args:
            - run
            - --bind-all
          ports:
            - containerPort: 8080
              name: http-api
      volumes:
        - name: wallet-config
          configMap:
            name: wallet-config
        - name: wallet-data
          persistentVolumeClaim:
            claimName: wallet-data-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: walletkit
spec:
  selector:
    app: walletkit
  ports:
    - port: 8092
      targetPort: 8080
  type: LoadBalancer
